language: c
compiler: gcc

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install -y libjack-jackd2-dev libjson-c-dev
    - sudo apt-get install -y jackd2

script:
    - make
    - sudo make install
    - cd test
    - make
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - jackd -d dummy &
    - bash runTests.sh
